[package]
name = "rustings"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#  fast conversion of integer primitives to decimal strings
itoa = "1.0.9"
log = "0.4.20"

